Redesign content usage table
fortedigital/Optimizely.ContentUsage pull request #69
Opened 2023-08-09 11:43 UTC by Fifok

According to #61

I redesign content usages table.

I also split ContentTypeUsageView.tsx into content usage table components.

2023-08-16 12:01 UTC, mgorzanski commented
@darekhalecki suggested to add an edit on hover:
![image](https://github.com/fortedigital/Optimizely.ContentUsage/assets/7347107/467d0b6f-93d9-4ca2-b9ad-f1b95fae5449)

2023-08-16 12:09 UTC, mgorzanski requested changes

2023-08-16 12:09 UTC, mgorzanski commented on src/Forte.Optimizely.ContentUsage/Frontend/Components/Tables/PageUrlCell/PageUrlCell.tsx
> +const PageUrlCell = ({pageUrls}:{pageUrls: string[]}) => {
Please add an interface for props

2023-08-16 12:09 UTC, mgorzanski commented on src/Forte.Optimizely.ContentUsage/Frontend/Views/ContentTypeUsageView.scss
> +    .oui-disclose__content {
I think you missed `&` here:
```suggestion
    & .oui-disclose__content {
```

2023-08-16 12:09 UTC, mgorzanski commented on src/Forte.Optimizely.ContentUsage/Frontend/Views/ContentTypeUsageView.tsx
> +                <ContentTypeUsagesTable rows={rows} tableColumns={tableColumns} sortDirection={sortDirection.toLowerCase()} onSortChange={handleSortChange}/>
Please add separate lines for each of the props

2023-08-16 12:32 UTC, Fifok commented
> 
Oh! I misunderstood that comment. Now I get it. I'll add it.

2023-08-16 12:35 UTC, Fifok commented
> @darekhalecki suggested to add an edit on hover: ![image](https://user-images.githubusercontent.com/7347107/261001033-467d0b6f-93d9-4ca2-b9ad-f1b95fae5449.png)

I misunderstood that comment! Now I get it and will add it.

2023-08-18 08:50 UTC, mgorzanski requested changes

2023-08-18 08:50 UTC, mgorzanski commented on src/Forte.Optimizely.ContentUsage/Frontend/Components/Tables/ContentTypeUsagesTable/ContentTypeUsageTableRow/ContentTypeUsageTableRow.tsx
> +      <Table.TR class="forte-optimizely-content-usage-table-row" onRowClick={onRowClick}>
should be
```suggestion
      <Table.TR className="forte-optimizely-content-usage-table-row" onRowClick={onRowClick}>
```

2023-08-18 08:50 UTC, mgorzanski commented on src/Forte.Optimizely.ContentUsage/Frontend/Components/Tables/ContentTypeUsagesTable/ContentTypeUsageTableRow/ContentTypeUsageTableRow.tsx
> +          <Table.TD colSpan={column.columnSpanWidth}>
missing `key` here

2023-08-25 13:56 UTC, mgorzanski approved these changes

2023-08-28 06:19 UTC, merged